permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "assets/img"
    values:
      image: true

# This is needed for styling the table of contents
kramdown:
  parse_block_html: true
